services:
  # 主要服務
  app:
    build: .
    ports:
      - "8080:8080"
  #  服務啟動順序設定
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/allieatfinal_db01?serverTimezone=Asia/Taipei&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    volumes:
      - ./upload:/app/upload
    restart: on-failure

  # MySQL 資料庫
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
  #  環境變數設定
    environment:
      MYSQL_DATABASE: allieatfinal_db01
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Taipei
      LANG: C.UTF-8
      MYSQL_ROOT_HOST: "%"
  #    uft8mb4 設定 與 表格大小寫不敏感設定
    command: >
      mysqld
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
  #      測試與重連
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
